#ifndef __TRUMP2025_TARIFFS_H__
#define __TRUMP2025_TARIFFS_H__

/* Generated by programs/python/trump2025_tariffs.py.
   Source repo commit: 6f2bf4af885ca2e0c5a37c6f868d487559228f32
   Target date: 2025-12; baseline year: 2024.
   Concordance method: isic. */

static const double trump2025_tau[NS][NC] = {
  {0.0, 0.280397673366, 0.048261135371}, /* UPH */
  {0.0, 0.192260444103, 0.125399081760}, /* UPL */
  {0.0, 0.159994934464, 0.086466418532}, /* DNH */
  {0.0, 0.226998419414, 0.086100996172}, /* DNL */
  {0.0, 0.0, 0.0}, /* SVC */
  {0.0, 0.0, 0.0}  /* CNS */
};

#endif
