#ifndef __TRUMP2025_TARIFFS_H__
#define __TRUMP2025_TARIFFS_H__

/* Generated by programs/python/trump2025_tariffs.py.
   Source repo commit: 6f2bf4af885ca2e0c5a37c6f868d487559228f32
   Target date: 2025-12; baseline year: 2024. */

static const double trump2025_tau[NS][NC] = {
  {0.0, 0.278877820649, 0.043489174240}, /* UPH */
  {0.0, 0.192635620317, 0.126650960038}, /* UPL */
  {0.0, 0.161446722505, 0.085404643181}, /* DNH */
  {0.0, 0.223509376208, 0.087373773872}, /* DNL */
  {0.0, 0.0, 0.0}, /* SVC */
  {0.0, 0.0, 0.0}  /* CNS */
};

#endif
